### ISSUE TITLE
npm ERR! Invalid package name "npm in" of package "npm in@^1.0.17": 

### ISSUE THREAD

**Issue by Molnfront** [3DJakob/react-tinder-card#147]
It has worked before. But now when I try:

npm install --save react-tinder-card
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "npm in" of package "npm in@^1.0.17": name can only contain URL-friendly characters.

The log file:
41 verbose stack Error: Invalid package name "npm in" of package "npm in@^1.0.17": name can only contain URL-friendly characters.
41 verbose stack     at invalidPackageName (/Users/moset/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:90:15)
41 verbose stack     at Result.setName (/Users/moset/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:129:11)
41 verbose stack     at new Result (/Users/moset/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:119:10)
41 verbose stack     at Function.resolve (/Users/moset/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:56:15)
41 verbose stack     at Arborist.[nodeFromEdge] (/Users/moset/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1107:22)
41 verbose stack     at Arborist.[buildDepStep] (/Users/moset/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:976:36)
41 verbose stack     at Arborist.[buildDeps] (/Users/moset/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:824:31)
41 verbose stack     at Arborist.buildIdealTree (/Users/moset/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:29)
41 verbose stack     at async Promise.all (index 1)
41 verbose stack     at async Arborist.reify (/Users/moset/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
42 verbose cwd /Users/moset/tbvappsway_mars
43 verbose Darwin 22.3.0
44 verbose node v16.13.2
45 verbose npm  v8.13.1
46 error code EINVALIDPACKAGENAME
47 error Invalid package name "npm in" of package "npm in@^1.0.17": name can only contain URL-friendly characters.
48 verbose exit 1

**Comment by Molnfront** [comment]
Closing!

It was just some crap that had went into the package.json for some unknown reason..
